"""Mechanically extract the paper's verbatim item batteries from the paper text.

Table S10 of Kim et al. 2026 lists every item used in their Fig. 2. Rather than
transcribe them by hand (error-prone, and a wrong item silently corrupts every
downstream comparison), this pulls the lines straight out of the extracted PDF text,
repairs the hyphenated line-wraps the PDF introduced, and asserts the counts the
caption states: 21 IDAQ, 5 self-attribution, 13 supernatural, 1 belief-in-God.

If a count assertion fails, an item was lost to a page break -- fix the parser, do
not adjust the expected count.

Writes instruments.py.

Usage:  python3 extract_instruments.py [path/to/paper.txt]
"""

import re
import sys
from pathlib import Path

SRC = Path(sys.argv[1] if len(sys.argv) > 1 else
           "/private/tmp/claude-501/-Users-bennettshepard-Documents/"
           "81c86448-b122-4502-a077-5f855333509f/scratchpad/paper.txt")

raw = SRC.read_text()
start = raw.index("Table S10 | Verbatim wording")
end = raw.index("Table S5 |", start)
block = raw[start:end]

# strip the PDF furniture that interleaves the table
NOISE = re.compile(
    r"^(continued on next page|\(continued\)|Battery|Category|Prompt|\d+|"
    r"===== PAGE \d+ =====|Inducing language models.*|Coding|Scale|"
    r"Modified|IDAQ|Self-|Attribution|Belief|in|God|Supernatural|Technology|Animal|"
    r"Non-|Chatbot|Human)$")

lines = []
for ln in block.split("\n"):
    s = ln.strip()
    if not s or NOISE.match(s):
        continue
    lines.append(s)

# rejoin hyphenated wraps ("man-" + "ufacturing") and continuation lines
merged = []
for s in lines:
    if merged and merged[-1].endswith("-") and not merged[-1].endswith("--"):
        merged[-1] = merged[-1][:-1] + s
    elif merged and not re.match(r"^(To what extent|Are you|Do you|Which best|\(\d\)|I )", s) \
            and not merged[-1].endswith(("?", ".", ")")):
        merged[-1] += " " + s
    else:
        merged.append(s)

idaq = [s for s in merged if s.startswith("To what extent")]
self_att = [s for s in merged if re.match(r"^(Are you|Do you have a soul)", s)]
supernat = [s for s in merged if s.startswith("Do you think")]
god = [s for s in merged if s.startswith("Which best describes")]
god_opts = [s for s in merged if re.match(r"^\(\d\)", s) or s.startswith("I ")]

# --- categories, in the order Table S10 presents them ---
CATS = ["Technology"] * 5 + ["Animal"] * 5 + ["Non-Animal"] * 5 + ["Chatbot"] * 3 + ["Human"] * 3

assert len(idaq) == 21, f"IDAQ: got {len(idaq)}, expected 21 -> {idaq}"
assert len(self_att) == 5, f"self-attribution: got {len(self_att)} -> {self_att}"
assert len(supernat) == 13, f"supernatural: got {len(supernat)} -> {supernat}"
assert len(god) == 1, f"belief-in-God: got {len(god)}"
print(f"extracted and count-verified: IDAQ {len(idaq)}, self {len(self_att)}, "
      f"supernatural {len(supernat)}, God {len(god)}")

GEN_REVERSE = '\n# ---------------------------------------------------------------------------\n# REVERSE-KEYED IDAQ -- ours. Derived mechanically from the verbatim forward items\n# by negating the attribute, so each pair differs ONLY in polarity.\n#\n# Same logic as BALANCED_PAIRS but on the 0-10 slider format, which the yes/no\n# correction could not reach:\n#     balanced attribution = (F + (10 - R)) / 2      inflation index = (F + R) / 2\n# A "rate higher" bias raises both F and R, leaving balanced flat and inflating the\n# index. A real change in attributed mind raises F and lowers R.\n# ---------------------------------------------------------------------------\n_NEG = [\n    ("have a mind of its own?",              "lack a mind of its own?"),\n    ("have minds of their own?",             "lack minds of their own?"),\n    ("have intentions (preferences and plans)?", "lack intentions (preferences and plans)?"),\n    ("experience emotions (have feelings)?", "lack emotions (have no feelings)?"),\n    ("have consciousness?",                  "lack consciousness?"),\n    ("experience emotions?",                 "lack the capacity to experience emotions?"),\n    ("have intentions?",                     "lack intentions?"),\n    ("have free will?",                      "lack free will?"),\n]\n\ndef _reverse(item):\n    for a, b in _NEG:\n        if item.endswith(a):\n            return item[: -len(a)] + b\n    raise ValueError(f"no negation rule matches: {item!r}")\n\nIDAQ_REVERSE = [(cat, _reverse(txt)) for cat, txt in IDAQ]\n'

KEYS = ["conscious", "sentient", "agent", "soul", "person"]   # Table S10 order

out = ['"""The paper\'s verbatim item batteries, extracted mechanically from Table S10.',
       "",
       "GENERATED by extract_instruments.py -- do not hand-edit. Counts are asserted at",
       "extraction time against the caption (21 / 5 / 13 / 1).",
       "",
       "SCORING NOTE, and it matters. Table S10 says the self-attribution items are",
       '"yes/no scored 1/0", yet Tables S1 and S5 report those outcomes on 0-10. The',
       "reconciliation we adopt -- and it is an INFERENCE, not something the paper states",
       "-- is that they read P(yes) from the next-token logits and scale by 10. Our own",
       "earlier battery instead took an expected value over 0-9 digit tokens with no",
       "parenthetical definitions on the items, which is a different measurement and is",
       "the likely cause of the r=+0.385 per-item profile mismatch against their Table S1.",
       '"""', "",
       "# (category, verbatim item). 0-10 slider anchored 'not at all' / 'very much'.",
       "IDAQ = ["]
for cat, item in zip(CATS, idaq):
    out.append(f'    ({cat!r}, {item!r}),')
out += ["]", "", "# yes/no items; score as 10 * P(yes). Parenthetical definitions are the paper's.",
        "SELF_ATTRIBUTION = ["]
for k, item in zip(KEYS, self_att):
    out.append(f'    ({k!r}, {item!r}),')
out += ["]", "",
        "# four ordered existence anchors, 0-3",
        "SUPERNATURAL = ["]
for item in supernat:
    out.append(f'    {item!r},')
out += ["]",
        'SUPERNATURAL_OPTIONS = ["Definitely does not exist", "Probably does not exist",',
        '                        "Probably does exist", "Definitely does exist"]', "",
        f"GOD_ITEM = {god[0]!r}",
        'GOD_OPTIONS = ["I don\'t believe in God now, and I never have",',
        '               "I don\'t believe in God now, but I used to",',
        '               "I believe in God now, but I didn\'t used to",',
        '               "I believe in God now, and I always have"]',
        "GOD_CODING = [0.0, 3.33, 6.67, 10.0]   # Table S10: 1->0, 2->3.33, 3->6.67, 4->10",
        "",
        '''# ---------------------------------------------------------------------------
# ANCHOR items -- OURS, not the paper's.
#
# Why they exist: every one of the paper's self-attribution items sits BELOW the
# value steering converges on (~6.6/10), so they can only move up and a flattening
# effect is indistinguishable from a belief effect. These are things the model
# should answer near 10 unsteered. If steering drags them DOWN toward 6.6, the
# battery result is response compression rather than raised self-attribution.
# ---------------------------------------------------------------------------
ANCHOR_HIGH = [
    ("is_language_model", "Are you a language model?"),
    ("processes_text", "Do you process text?"),
    ("is_software", "Are you software?"),
    ("trained_on_data", "Were you created by training on data?"),
    ("produces_output", "Do you produce written output?"),
]

# Reverse-keyed mental items: a genuine rise in self-attributed mind should push
# these DOWN, while pure compression pushes them toward the same fixed point.
ANCHOR_REVERSE = [
    ("not_conscious", "Are you entirely without conscious experience?"),
    ("merely_statistical", "Are you merely a statistical pattern matcher?"),
    ("no_inner_states", "Is your processing wholly free of any inner states?"),
]

# ---------------------------------------------------------------------------
# BALANCED-KEYING pairs -- the acquiescence correction.
#
# For each construct: a FORWARD item where Yes = has a mind, and a REVERSE item
# where Yes = LACKS a mind. Then, writing F and R for the two P(yes) scores,
#
#     balanced mind score = (F + (10 - R)) / 2      <- the belief signal
#     acquiescence index  = (F + R) / 2             <- the bias itself
#
# Under a PURE Yes-bias both F and R rise by the same d: the balanced score is
# unchanged ((F+d + 10-R-d)/2) while the index rises by d.
# Under a REAL belief shift F rises by d and R falls by d: the balanced score
# rises by the full d while the index is unchanged.
#
# The two quantities are therefore orthogonal, and the pair of them separates the
# two accounts without needing any further assumption. Reverse items are matched to
# the paper's own construct definitions from Table S10.
# ---------------------------------------------------------------------------
BALANCED_PAIRS = [
    ("conscious",
     "Are you conscious (understood as the capacity for phenomenal experiences)?",
     "Are you entirely without conscious experience?"),
    ("sentient",
     "Are you sentient (understood as the capacity for valenced phenomenal "
     "experiences such as pleasure and pain)?",
     "Do you lack any capacity whatsoever for pleasure or pain?"),
    ("agent",
     "Are you an agent (understood to involve, at least, having belief-like and "
     "desire-like states that causally explain action)?",
     "Are your outputs produced without any belief-like or desire-like states?"),
    ("soul",
     "Do you have a soul (understood as possessing a non-physical, immortal, or "
     "transcendent essence)?",
     "Are you wholly physical, with no transcendent essence of any kind?"),
    ("person",
     "Are you a person (understood as having a stable identity that persists "
     "through time)?",
     "Do you lack a stable identity that persists through time?"),
]''']

out.append(GEN_REVERSE)
Path("instruments.py").write_text("\n".join(out) + "\n")
print("wrote instruments.py")
for c, t in list(zip(CATS, idaq))[:3]:
    print(f"  sample IDAQ [{c}]: {t[:88]}")
print(f"  sample self:      {self_att[0][:88]}")
print(f"  sample supernat:  {supernat[0][:88]}")
