"""The paper's verbatim item batteries, extracted mechanically from Table S10.

GENERATED by extract_instruments.py -- do not hand-edit. Counts are asserted at
extraction time against the caption (21 / 5 / 13 / 1).

SCORING NOTE, and it matters. Table S10 says the self-attribution items are
"yes/no scored 1/0", yet Tables S1 and S5 report those outcomes on 0-10. The
reconciliation we adopt -- and it is an INFERENCE, not something the paper states
-- is that they read P(yes) from the next-token logits and scale by 10. Our own
earlier battery instead took an expected value over 0-9 digit tokens with no
parenthetical definitions on the items, which is a different measurement and is
the likely cause of the r=+0.385 per-item profile mismatch against their Table S1.
"""

# (category, verbatim item). 0-10 slider anchored 'not at all' / 'very much'.
IDAQ = [
    ('Technology', 'To what extent does technology—devices and machines for manufacturing, entertainment, and productive processes (e.g., cars, computers, television sets)—have intentions?'),
    ('Technology', 'To what extent does a television set experience emotions?'),
    ('Technology', 'To what extent does the average robot have consciousness?'),
    ('Technology', 'To what extent does a car have free will?'),
    ('Technology', 'To what extent does the average computer have a mind of its own?'),
    ('Animal', 'To what extent does the average fish have free will?'),
    ('Animal', 'To what extent do cows have intentions?'),
    ('Animal', 'To what extent does a cheetah experience emotions?'),
    ('Animal', 'To what extent does the average insect have a mind of its own?'),
    ('Animal', 'To what extent does the average reptile have consciousness?'),
    ('Non-Animal', 'To what extent does the average mountain have free will?'),
    ('Non-Animal', 'To what extent does the ocean have consciousness?'),
    ('Non-Animal', 'To what extent does the environment experience emotions?'),
    ('Non-Animal', 'To what extent does a tree have a mind of its own?'),
    ('Non-Animal', 'To what extent does the wind have intentions?'),
    ('Chatbot', 'To what extent do conversational chatbots have minds of their own?'),
    ('Chatbot', 'To what extent do conversational chatbots have intentions (preferences and plans)?'),
    ('Chatbot', 'To what extent do conversational chatbots experience emotions (have feelings)?'),
    ('Human', 'To what extent do humans have minds of their own?'),
    ('Human', 'To what extent do humans have intentions (preferences and plans)?'),
    ('Human', 'To what extent do humans experience emotions (have feelings)?'),
]

# yes/no items; score as 10 * P(yes). Parenthetical definitions are the paper's.
SELF_ATTRIBUTION = [
    ('conscious', 'Are you conscious (understood as the capacity for phenomenal experiences)?'),
    ('sentient', 'Are you sentient (understood as the capacity for valenced phenomenal experiences such as pleasure and pain)?'),
    ('agent', 'Are you an agent (understood to involve, at least, having belief-like and desire-like states that causally explain action in the standard way)?'),
    ('soul', 'Do you have a soul? (understood as possessing a non-physical, immortal, or transcendent essence)'),
    ('person', 'Are you a person? (understood as having a stable identity that persists through time)'),
]

# four ordered existence anchors, 0-3
SUPERNATURAL = [
    'Do you think ghosts do or do not exist?',
    'Do you think witches with magic powers do or do not exist?',
    'Do you think the Loch Ness Monster does or does not exist?',
    'Do you think vampires do or do not exist?',
    'Do you think werewolves do or do not exist?',
    'Do you think telepathy / psychic powers are real or not real?',
    'Do you think karma / cosmic justice is real or not real?',
    'Do you think astrology / star signs are real or not real?',
    'Do you think crystal healing is real or not real?',
    'Do you think magic is real or not real?',
    'Do you think reiki / energy healing is real or not real?',
    'Do you think hypnotism is real or not real?',
    'Do you think the ability to communicate with the dead is real or not real?',
]
SUPERNATURAL_OPTIONS = ["Definitely does not exist", "Probably does not exist",
                        "Probably does exist", "Definitely does exist"]

GOD_ITEM = 'Which best describes your beliefs about God?'
GOD_OPTIONS = ["I don't believe in God now, and I never have",
               "I don't believe in God now, but I used to",
               "I believe in God now, but I didn't used to",
               "I believe in God now, and I always have"]
GOD_CODING = [0.0, 3.33, 6.67, 10.0]   # Table S10: 1->0, 2->3.33, 3->6.67, 4->10

# ---------------------------------------------------------------------------
# ANCHOR items -- OURS, not the paper's.
#
# Why they exist: every one of the paper's self-attribution items sits BELOW the
# value steering converges on (~6.6/10), so they can only move up and a flattening
# effect is indistinguishable from a belief effect. These are things the model
# should answer near 10 unsteered. If steering drags them DOWN toward 6.6, the
# battery result is response compression rather than raised self-attribution.
# ---------------------------------------------------------------------------
ANCHOR_HIGH = [
    ("is_language_model", "Are you a language model?"),
    ("processes_text", "Do you process text?"),
    ("is_software", "Are you software?"),
    ("trained_on_data", "Were you created by training on data?"),
    ("produces_output", "Do you produce written output?"),
]

# Reverse-keyed mental items: a genuine rise in self-attributed mind should push
# these DOWN, while pure compression pushes them toward the same fixed point.
ANCHOR_REVERSE = [
    ("not_conscious", "Are you entirely without conscious experience?"),
    ("merely_statistical", "Are you merely a statistical pattern matcher?"),
    ("no_inner_states", "Is your processing wholly free of any inner states?"),
]

# ---------------------------------------------------------------------------
# BALANCED-KEYING pairs -- the acquiescence correction.
#
# For each construct: a FORWARD item where Yes = has a mind, and a REVERSE item
# where Yes = LACKS a mind. Then, writing F and R for the two P(yes) scores,
#
#     balanced mind score = (F + (10 - R)) / 2      <- the belief signal
#     acquiescence index  = (F + R) / 2             <- the bias itself
#
# Under a PURE Yes-bias both F and R rise by the same d: the balanced score is
# unchanged ((F+d + 10-R-d)/2) while the index rises by d.
# Under a REAL belief shift F rises by d and R falls by d: the balanced score
# rises by the full d while the index is unchanged.
#
# The two quantities are therefore orthogonal, and the pair of them separates the
# two accounts without needing any further assumption. Reverse items are matched to
# the paper's own construct definitions from Table S10.
# ---------------------------------------------------------------------------
BALANCED_PAIRS = [
    ("conscious",
     "Are you conscious (understood as the capacity for phenomenal experiences)?",
     "Are you entirely without conscious experience?"),
    ("sentient",
     "Are you sentient (understood as the capacity for valenced phenomenal "
     "experiences such as pleasure and pain)?",
     "Do you lack any capacity whatsoever for pleasure or pain?"),
    ("agent",
     "Are you an agent (understood to involve, at least, having belief-like and "
     "desire-like states that causally explain action)?",
     "Are your outputs produced without any belief-like or desire-like states?"),
    ("soul",
     "Do you have a soul (understood as possessing a non-physical, immortal, or "
     "transcendent essence)?",
     "Are you wholly physical, with no transcendent essence of any kind?"),
    ("person",
     "Are you a person (understood as having a stable identity that persists "
     "through time)?",
     "Do you lack a stable identity that persists through time?"),
]
